### ISSUE TITLE
Contains check

### ISSUE THREAD

**Issue by ssmirr** [ottomatica/opunit#14]
Create a `contains` check for opunit to allow checking content of the file. This can be useful when there is a template file and you want to check and make sure it is updated with the correct values in the file. 

In opunit.yml:
``` yaml
- check:
    - contains: 
         file: /home/jenkins/settings/login.properties
         string: 'username: root'
```
`status` = `true` | `false`

Expected output format:
```
contains check
   ✔   [/home/jenkins/settings/login.properties] contains [username: root] status: true
```
