### ISSUE TITLE
Inventory applying checks on multiple instances

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/opunit#16]
Can use a simple inventory file to store ip addresses, user names, ssh-keys, etc.

Can include proposed format and design in comments.

**Comment by ssmirr** [comment]
I think using yaml format makes sense for now. We can add support for other formats in the future.

Proposed format for inventory:
``` yml
---
- docker:
  - name: trusting_lamport
- vagrant:
  - name: opunit-test
- ssh:
  - address: vagrant@127.0.0.1:2222
    private_key: ./private_key
    criteria_path: ../../opunit.yml
- baker:
  - name: hibernate-spring
    address: ~/projects/baker-examples/hibernate-spring
  - name: hibernate-spring2
    address: ~/projects/baker-examples/hibernate-spring
    criteria_path: ./opunit.yml
```

Command for running with inventory file:
``` shell
opunit verify -i ./inventory.yml
```


**Note:** The criteria path priority is:
 1. what you set in inventory file. 
 2. what you specify with `-c`  or `--criteria_path`
 3. `${cwd}/test/opunit.yml`
