### ISSUE TITLE
Capability checks.

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/opunit#20]
`capability` checks for sufficient ram, free space, # cpus, etc. on instance.

**Comment by ssmirr** [comment]
Proposing this format, the amounts are "at least" this much:

```
    checks:
      - capability:          
          - disk: /
             amount: 8000
          - cores: 2
          -  memory: 2000
```
