### ISSUE TITLE
Remove jq report output for without jq property.

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/opunit#204]
The following checks should not include jq output, given no jq is provided:
```
	contains check
		Checking if you have MSDOS style newlines in your bash scripts. Fix with dos2unix
	    ✔   [...run-ansible.sh] jq query: undefined does not contain: [\r] status: true message: NA
	contains check
	    ✔   [...config.json] jq query: undefined  contains: ["DriverName": "mysql"] status: true message: NA
```

Given these checks:

```yaml
      - contains:
          comment: Checking if you have MSDOS style newlines in your bash scripts. Fix with dos2unix
          string: "\r"
          expect: false
          file: /bakerx/cm/run-ansible.sh
      - contains:
         file: /opt/mattermost/config/config.json
         string: '"DriverName": "mysql"'
```
