### ISSUE TITLE
`java -version` unable to be matched by semver

### ISSUE THREAD

**Issue by ssmirr** [ottomatica/opunit#225]
**Describe the bug**
`java -version` unable to be matched by semver

**To Reproduce**

opunit.yml:
```
      - version:
         cmd: java -version
         range: ^1.11.x
      - version:
         cmd: javac -version
         range: ^1.11.x
```

```bash
vagrant@ubuntu-bionic:~$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

vagrant@ubuntu-bionic:~$ javac -version
javac 1.8.0_242
```

opunit report:
```
        version check
            ✔   java -version: 25.242.0 > ^1.11.x => true
        version check
            ✖   javac -version: javac 1.8.0_242 > ^1.11.x => false
```

**Expected behavior**
```
        version check
            ✖   java -version: 1.8.0 > ^1.11.x => false
        version check
            ✖   javac -version: 1.8.0 > ^1.11.x => false
```

**Please complete the following information:**
 - Version: #dev
