### ISSUE TITLE
Service check

### ISSUE THREAD

**Issue by ssmirr** [ottomatica/opunit#3]
In `opunit.yml`:
```
- service:
   name: mysql
   status: active
- service:
   name: shouldntexist
   status: none
```
`status` = `active` | `inactive` | `none`

Expected output:
```
service check
      ✔   [mysql] expected: active actual: active
service check
      ✔   [shouldntexist] expected: none actual: none
```
