### ISSUE TITLE
Error: Cannot find module './command' when command check

### ISSUE THREAD

**Issue by billmetangmo** [ottomatica/opunit#342]
I found this project from an article on https://link.springer.com/chapter/10.1007/978-3-030-39306-9_12 and found it very instresrting :) .
So I decided to use it to verify requirements steps of one project . It works like a charm except the command excec.
Here's the bug details:

**Describe the bug**
I wanted to execute an opunit verify with local connector using command check but it fails.

**To Reproduce**
1. Use the opunit.yml below:
```
- group:
    description: "Installation check"
    checks:
      - version:
         cmd: git --version
         range: ^2.x.x
      - version:
          cmd: make --version
          range: ^4.1
      - version:
          cmd: python --version
          range: ^3.7.3
      - version:
          cmd: direnv --version
          range: ^2.22.0
      - version:
          cmd: terraform --version
          range: ^0.13.2
      - version:
          cmd: netcat -h
          range: ^x.x
      - version:
          cmd: docker version
          range: ^x.x

- group:
    description: "Configuration check"
    checks:
      - reachable:
          - .direnv
          - .env.scw
          - .env.r5p

      - contains:
          file: .env.r5p
          string: 'RED5PRO_SM_DNS'

      - contains:
          file: .env.r5p
          string: 'RED5PRO_SM_TOKEN'

      - contains:
          file: .env.r5p
          string: 'RED5PRO_SERVER_TOKEN'

      - contains:
          file: .env.scw
          string: 'SCW_DEFAULT_ORGANIZATION_ID'

      - contains:
          file: .env.scw
          string: 'SCW_ACCESS_KEY'

      - contains:
          file: .env.scw
          string: 'SCW_SECRET_KEY'

      - contains:
          file: .env.scw
          string: SCW_DEFAULT_REGION="fr-par"

      - contains:
          file: .env.scw
          string: SCW_DEFAULT_ZONE="fr-par-1"

      - command:
          exec: echo 'FOO'
          stdout: FOO
```

2. Run `opunit verify` , you will get this error
```

Error: Cannot find module './command'
Require stack:
- /home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/lib/inspect/checks/loader.js
- /home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Loader.resolveModule (/home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/lib/inspect/checks/loader.js:22:22)
    at Loader.loadChecks (/home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/lib/inspect/checks/loader.js:36:35)
    at async verify (/home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/index.js:19:18)
    at async main (/home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/index.js:42:5)
    at async Object.handler (/home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/index.js:239:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/lib/inspect/checks/loader.js',
    '/home/bafou/.nvm/versions/node/v14.14.0/lib/node_modules/opunit/index.js'
  ]
}

```

**Expected behavior**
Should print FOO in console

**Please complete the following information:**
 - OS ( WSL2 windows) : 
```
   Distributor ID: Ubuntu
   Description:    Ubuntu 18.04.5 LTS
   Release:        18.04
   Codename:       bionic
```

 - NodeJS ( output of nvm ls)
```
->     v14.14.0
default -> node (-> v14.14.0)
node -> stable (-> v14.14.0) (default)
stable -> 14.14 (-> v14.14.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.22.1 (-> N/A)
lts/erbium -> v12.19.0 (-> N/A)
```

Thanks
