### ISSUE TITLE
Availability check for ssh targets

### ISSUE THREAD

**Issue by ssmirr** [ottomatica/opunit#426]
**Describe the bug**
The availability check seems to check local machine even when used with a ssh target

**To Reproduce**
Here is an opunit check:
```yaml
 - availability:
      comment: check app running in the vm
      port: 5001
      status: 200
      url: /
```
and inventory file:
```yaml
- ssh:
  - target: vagrant@127.0.0.1:2800
    private_key: ~/id_rsa
    criteria_path: test/vm.yml
```

**Expected behavior**
Expected to check if localhost:5001 server is running inside the vm.

**Actual behavior**
It check localhost:5001 on the local machine.
